title: ![Amit Vikram Raj](https://in.linkedin.com/in/avr27?trk=profile-badge)
logo: /assets/img/photo-circle-crop.png
#description: [LinkedIn](https://www.linkedin.com/in/amit-vikram-raj-883460207/)
show_downloads: false
theme: jekyll-theme-minimal
