title: Amit Vikram Raj
logo: /assets/img/photo-circle-crop.png
description: I'm an aspiring Machine Learning Engineer. This is my Portfolio. Connect with me on <a href="https://www.linkedin.com/in/avr27/" target="_blank">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
